name: pages-build-site
on: 
  push:  // 有代码push或者merge到main分支时，才进行下面的操作
    branches: 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      

      - name: Install dependencies
        run: yarn install

      - name: Build docs
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTION_SECERT }} // 配置在项目里的secrets
          exclude_assets: ''
          publish_dir: /docs/.vitepress/dist // 需要发布内容的路径